[color-theme]
name = "Everblush Theme"

[color-theme.base]
white = "#dadada"
black = "#141b1e"
grey = "#232a2d"
blue = "#67b0e8"
red = "#e57474"
yellow = "#e5c76b"
orange = "#ef9667"
green = "#8ccf7e"
purple = "#9e6399"
cyan = "#6cbfbf"
magenta = "#c47fd5"

[color-theme.syntax]
attribute = "$yellow"
builtinType = "$cyan"
comment = "#5c705e"
constant = "$yellow"
constructor = "$yellow"
embedded = "$cyan"
enum = "$yellow"
enum-member = "$red"
enumMember = "$red"
escape = "$cyan"
field = "$red"
function = "$purple"
"function.method" = "$blue"
interface = "$yellow"
keyword = "$cyan"
"keyword.control" = "$purple"
method = "$blue"
number = "$magenta"
property = "$red"
"punctuation.delimiter" = "$yellow"
selfKeyword = "$purple"
string = "$green"
"string.escape" = "$cyan"
struct = "$yellow"
structure = "$yellow"
symbol = "$yellow"
tag = "$blue"
"text.reference" = "$yellow"
"text.title" = "$orange"
"text.uri" = "$cyan"
type = "$yellow"
"type.builtin" = "$cyan"
typeAlias = "$yellow"
variable = "$orange"
"variable.other.member" = "$green"

[color-theme.ui]
"activity.background" = "#21252B"
"activity.current" = "$black"
"completion.background" = "#21252B"
"completion.current" = "#2C313A"
"editor.background" = "$black"
"editor.caret" = "$blue"
"editor.current_line" = "$grey"
"editor.dim" = "#5C6370"
"editor.drag_drop_background" = "#79c1fc55"
"editor.drag_drop_tab_background" = "#0b0e1455"
"editor.focus" = "#CCCCCC"
"editor.foreground" = "$white"
"editor.indent_guide" = "$grey"
"editor.link" = "$blue"
"editor.selection" = "#495654"
"editor.sticky_header_background" = "$black"
"editor.visible_whitespace" = "$grey"
"error_lens.error.background" = "#E06C7520"
"error_lens.error.foreground" = "$red"
"error_lens.other.background" = "#5C637020"
"error_lens.other.foreground" = "#5C6370"
"error_lens.warning.background" = "#E5C07B20"
"error_lens.warning.foreground" = "$yellow"
"hover.background" = "#21252B"
"inlay_hint.background" = "#528abF37"
"inlay_hint.foreground" = "$white"
"lapce.border" = "$grey"
"lapce.button.primary.background" = "#50a14f"
"lapce.button.primary.foreground" = "$black"
"lapce.dropdown_shadow" = "#000000"
"lapce.error" = "$red"
"lapce.icon.active" = "$white"
"lapce.icon.inactive" = "#5C6370"
"lapce.plugin.author" = "#B0B0B0"
"lapce.plugin.description" = "$white"
"lapce.plugin.name" = "$blue"
"lapce.remote.connected" = "#50A14F"
"lapce.remote.connecting" = "$orange"
"lapce.remote.disconnected" = "$red"
"lapce.remote.local" = "#4078F2"
"lapce.scroll_bar" = "$grey"
"lapce.tab.active.background" = "$black"
"lapce.tab.active.foreground" = "$white"
"lapce.tab.active.underline" = "#528BFF"
"lapce.tab.inactive.background" = "#21252b"
"lapce.tab.inactive.foreground" = "$white"
"lapce.tab.inactive.underline" = "#528BFF77"
"lapce.tab.separator" = "$grey"
"lapce.warn" = "$yellow"
"markdown.blockquote" = "$grey"
"palette.background" = "#21252B"
"palette.current.background" = "#2C313A"
"palette.current.foreground" = "$white"
"palette.foreground" = "$white"

"panel.background" = "#171c1e"
"panel.current.background" = "$black"
"panel.current.foreground" = "$white"
"panel.current.foreground.dim" = "#5c6d70"
"panel.foreground" = "$white"
"panel.foreground.dim" = "#5C6370"
"panel.hovered.background" = "$grey"
"panel.hovered.foreground" = "$white"
"panel.hovered.foreground.dim" = "#5C6370"

"source_control.added" = "#50A14F32"
"source_control.modified" = "#0184BC32"
"source_control.removed" = "#FF526632"
"status.background" = "#21252B"
"status.foreground" = "$white"
"status.modal.insert" = "$red"
"status.modal.normal" = "$blue"
"status.modal.terminal" = "$purple"
"status.modal.visual" = "$yellow"

"terminal.background" = "$black"
"terminal.black" = "$black"
"terminal.blue" = "$blue"
"terminal.bright_black" = "#545862"
"terminal.bright_blue" = "$blue"
"terminal.bright_cyan" = "$cyan"
"terminal.bright_green" = "$green"
"terminal.bright_magenta" = "$magenta"
"terminal.bright_red" = "$red"
"terminal.bright_white" = "#C8CCD4"
"terminal.bright_yellow" = "$yellow"
"terminal.cursor" = "$white"
"terminal.cyan" = "$cyan"
"terminal.foreground" = "$white"
"terminal.green" = "$green"
"terminal.magenta" = "$magenta"
"terminal.red" = "$red"
"terminal.white" = "$white"
"terminal.yellow" = "$yellow"

[ui]
font-family = ""
font-size = 13
icon-size = 0
header-height = 35
status-height = 20
tab-min-width = 100
scroll-width = 10
drop-shadow-width = 0
preview-editor-width = 0
hover-font-family = ""
hover-font-size = 0
