name = "everblush"
display-name = "Everblush"
description = "Everblush theme for Lapce"
version = "0.1.0"
author = "incognitux"
repository = "https://github.com/Incognitux/Lapce-Everblush"
icon = "assets/logo.png"
color-themes = ["everblush.toml"]
